### ISSUE TITLE
missed model image Or damage url

### ISSUE THREAD

**Issue by asd-4soft** [TwrpBuilder/twrpbuilder.github.io#9]
```code
This link is not working please update the link Or upload again, thanks.
model : HUAWEI Y336-U02
codename : Y336-U02
```
https://basketbuild.com/uploads/devs/yshalsager/TwrpBuilder/huawei/y336_u02/TWRP-3.2.2-y336_u02-20180728.img

**Comment by yshalsager** [comment]
> ```
> This link is not working please update the link Or upload again, thanks.
> model : HUAWEI Y336-U02
> codename : Y336-U02
> ```
> 
> https://basketbuild.com/uploads/devs/yshalsager/TwrpBuilder/huawei/y336_u02/TWRP-3.2.2-y336_u02-20180728.img

Basketbuild site is down, unfortunately we can do nothing.
If this device has its device tree pushed at @TwrpBuilder or @TwrpBuilderTests you can build it on your own.
Sorry about that!
